name: oci

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  oci:
    name: 'oci_policies_validation'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
  
    - name: setup
      run: |
        echo hello world
        ls -lt
        pwd
        cat config
        sed -i "s/OCI_USER_ID/${{vars.OCI_USER_ID}}/g" "config"
        sed -i "s/OCI_FINGER_PRINT_ID/${{vars.OCI_FINGER_PRINT_ID}}/g" "config"
        sed -i "s/OCI_TENANCY_ID/${{vars.OCI_TENANCY_ID}}/g" "config"
        sed -i "s/OCI_REGION/${{vars.OCI_REGION}}/g" "config"
        cat config
        sudo apt update && sudo apt upgrade -y
        sudo apt install python3
        pip install oci-cli
        pip install oci
        wget https://releases.hashicorp.com/terraform/1.4.1/terraform_1.4.1_linux_amd64.zip
        sudo unzip terraform_1.4.1_linux_amd64.zip -d /usr/local/bin <<< "y"
        oci setup repair-file-permissions --file /home/runner/work/OCIPolicyMgmt/OCIPolicyMgmt/config
        oci setup repair-file-permissions --file /home/runner/work/OCIPolicyMgmt/OCIPolicyMgmt/oci_api_key.pem 
        python --version
   
    - name: Terraform Init
      run: |
        echo hello world
        ls -lt
        cd terraform
        ls -lt
        rm -rf .terraform
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        export fingerprint=${{ vars.OCI_FINGER_PRINT_ID }}
        export private_key_path=${{ vars.OCI_PRIVATE_KEY_PATH }}
        export user_ocid=${{ vars.OCI_USER_ID }}
        export tenancy_ocid=${{ vars.OCI_TENANCY_ID }}
        export compartment_ocid=${{ vars.OCI_COMPARTMENT_ID }}
        terraform init
        terraform apply -auto-approve
