name: oci

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  oci:
    name: 'oci_policies_validation'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
  
    - name: simple command line test
      run: |
        echo hello world
