name: oci

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  oci:
    name: 'oci_policies_validation'
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Checkout
      uses: actions/checkout@v3
  
    - name: simple command line test
      run: |
        echo hello world
        ls -lt
        echo ${{ secrets.OCI_USER_ID }}
        echo ${{ secrets.OCI_TENANCY_ID }}
        echo ${{ vars.OCI_REGION }}
        #sudo apt update && sudo apt upgrade -y
        #sudo apt install python3
        #pip install oci-cli
        #wget https://releases.hashicorp.com/terraform/1.4.1/terraform_1.4.1_linux_amd64.zip
        #sudo unzip terraform_1.4.1_linux_amd64.zip -d /usr/local/bin <<< "y"
        #oci --help
        #terraform --help
        #terraform --version
        #oci --version
        #python --version
